seed: 1234

data:
  name: CelebA-HQ
  dataroot: /data/CelebA-HQ/
  img_size: 256

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  micro_batch: 0

mask:
  mask_type: dir
  dir_path: /data/NVIDIAIrregularMaskDataset/train/
  dir_invert_color: true

model:
  n_layers: 8

train:
  n_steps: 70000
  batch_size: 12
  pretrained: ~
  resume: ~
  print_freq: 100
  save_freq: 5000
  eval_freq: 1000
  sample_freq: 1000

  coef_valid: 1.0
  coef_hole: 6.0
  coef_perceptual: 0.05
  coef_style: 120
  coef_tv: 0.1

  optim:
    lr: 0.00005
    betas: [0.5, 0.999]
